### ISSUE TITLE
gtk_status_icon_position_menu is deprecated

### ISSUE THREAD

**Issue by tho068** [fernandotcl/pa-applet#11]
This fails to build on GTK 3.13 due to the usage of a deprecated function.

 `test -f 'popup_menu.c' || echo './'`popup_menu.c
popup_menu.c: In function ‘show_popup_menu’:
popup_menu.c:98:5: error: ‘gtk_status_icon_position_menu’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:160) [-Werror=deprecated-declarations]
     gtk_menu_popup(GTK_MENU(menu), NULL, NULL, gtk_status_icon_position_menu,
     ^
cc1: all warnings being treated as errors
Makefile:465: recipe for target 'pa_applet-popup_menu.o' failed
make[2]: **\* [pa_applet-popup_menu.o] Error 1
make[2]: Leaving directory '/tmp/yaourt-tmp-thomas/aur-pa-applet-git/src/pa-applet-git/src'
Makefile:357: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-thomas/aur-pa-applet-git/src/pa-applet-git'
Makefile:297: recipe for target 'all' failed

Also, it seems like GTK is going to drop support for sys tray icons. Atleast I read that somewhere I thnik.

**Comment by LeoKSimon** [comment]
Hi, would somebody mind explaining in more detail exactly what file and lines are commented out in order to deactivate the error message to make this work?     I'm surprised that 2 years later this is still an issue?  I'm running Ubuntu 16.04.      Thanks very much for any help:     Here in detail is the output from make:

root@E5570:local/src/pa-applet-master#make
make  all-recursive
make[1]: Entering directory '/usr/local/src/pa-applet-master'
Making all in man
make[2]: Entering directory '/usr/local/src/pa-applet-master/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/local/src/pa-applet-master/man'
Making all in src
make[2]: Entering directory '/usr/local/src/pa-applet-master/src'
gcc -DHAVE_CONFIG_H -I. -I..  -std=c99 -D_GNU_SOURCE -Wall -Werror -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_REENTRANT -D_REENTRANT -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include    -g -O2 -MT pa_applet-popup_menu.o -MD -MP -MF .deps/pa_applet-popup_menu.Tpo -c -o pa_applet-popup_menu.o `test -f 'popup_menu.c' || echo './'`popup_menu.c
popup_menu.c: In function ‘show_popup_menu’:
popup_menu.c:98:5: error: ‘gtk_status_icon_position_menu’ is deprecated [-Werror=deprecated-declarations]
     gtk_menu_popup(GTK_MENU(menu), NULL, NULL, gtk_status_icon_position_menu,
     ^
In file included from /usr/include/gtk-3.0/gtk/gtk.h:261:0,
                 from popup_menu.c:10:
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:160:23: note: declared here
 void                  gtk_status_icon_position_menu      (GtkMenu            *menu,
                       ^
cc1: all warnings being treated as errors
Makefile:475: recipe for target 'pa_applet-popup_menu.o' failed
make[2]: *** [pa_applet-popup_menu.o] Error 1
make[2]: Leaving directory '/usr/local/src/pa-applet-master/src'
Makefile:367: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/pa-applet-master'
Makefile:308: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mschwager** [comment]
I'm currently getting this error on Ubuntu 16.04 as well.

Though, the suggested patch fixes it. @LeoKSimon you have to make this change: https://github.com/Strubbl/pa-applet/commit/451f68353ffad9c4cf988a022cb92864655fd7f1

It'd be awesome if this code was either updated to avoid the deprecated function (preferable), or the warning was squelched!

**Comment by mschwager** [comment]
I've also forked this project and included this fix (among other things): https://github.com/mschwager/pa-applet
